### PR TITLE
Search similar images from embedding space

### PR DESCRIPTION
**Pull request by haseeb33**
Hey Zhenye!
Amazing Work! I learned a lot from this implementation of yours. The code is very clean and easily interpretable.

I struggled in preform inference task as mentioned by other as well ([Inference #10](https://github.com/Zhenye-Na/image-similarity-using-deep-ranking/issues/10)). I can't write as clear code as yours but I tried to write the code for this task.

**Now Inference can be performed using the added code.**

### CODE REVIEW

**Comment by Zhenye-Na** [comment]
Hello @haseeb33,

Thank you for creating this PR, as I saw many people are requesting this, but it is hard for me to remember the details to do the "math", since this is actually a graduate school work.


I reviewed your code and I saw you are using kd-tree as the data structure or algorithm to accomplish, I think it should be on the right track. I think your codes are very clear to show what you try to achieve. Good job!

I definitely would love to approve your PR if you could also :

1. maybe replace the images in `README.md` with your implementation results, either from terminal or you have a GUI, both works ?
2. maybe paste the commands in `README.md` so that people can directly grab and use ?

those are just tentative suggestions, if you dont have time, no worries at all.

Thank you for the hard work!

Best regards,
Zhenye

**Comment by haseeb33** [comment]
Thank you for such encouraging words and tentative suggestions for a better understanding of codebase. 
I shall try to work on these points soon.

Best Regards!
Haseeb

**Comment by Zhenye-Na** [comment]
Thank you!

**Comment by haseeb33** [comment]
Hi Zhenye!

I have updated ```README``` file as well as modified a little bit of ```acc_knn.py file``` to implement and show the searching functionality.

Best Regards!
Haseeb

**Comment by Zhenye-Na** [comment]
Very well done! Thank you Haseeb!

merged to master branch now.

**Pull request merged**
